### ISSUE TITLE
Just wanted to say something. 

### ISSUE THREAD

**Issue by ReneFroger** [hlissner/emacs.d#1]
Hi Henrik, 

Just only saying that I found your .emacs-configuration very inspirational, next to [this one](http://doc.rix.si/org/fsem.html).

However, I noticed you don't use the server-feature of Emacs. You should definitely give it a try (on Windows it works fine too), it's so convenient. And I've just started reading a few random sections of your config, there's already so many cool snippets I'm definitely studying/stealing.

Thanks for the inspiration, it's appreciated!

**Comment by hlissner** [comment]
Thank you! I'm happy that it's helped you.

> I noticed you don't use the server-feature of Emacs

Actually, I am using it. I start the server at the bottom of `core/core.el` -- it's been in the project in one form or another since the start. I agree, it's very useful!

I update my emacs.d very frequently, so feel free to check back anytime!

**Comment by ReneFroger** [comment]
Sorry, I didn't saw it earlier. Thank you, there is a Reddit topic about sharing the Emacs configurations, might be relevant.
